[package]
name = "iroh-gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.2"
tokio = { version = "1", features = ["full"] }
headers = { version = "0.4" }
hyper = "1"
bytes = "1.1"
iroh = "0.12.0"
range-collections = "0.4.5"
anyhow = "1.0.75"
flume = "0.11.0"
tracing = "0.1.40"
tower-http = "0.4.4"
clap = { version = "4.4.7", features = ["derive"] }
mime_classifier = "0.0.1"
derive_more = { version = "1.0.0-beta.1", features = ["debug"] }
mime = "0.3.17"
quinn = "0.10.2"
url = "2.4.1"
futures = "0.3.29"
tower = "0.4.13"
