[package]
name = "iroh-content-tracker"
version = "0.1.0"
edition = "2021"
description = "Simple content tracker server for iroh"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iroh = "0.11.0"
serde = { version = "1", features = ["derive"] }
